### ISSUE TITLE
Reading SConsript files throughs AttributeError

### ISSUE THREAD

**Issue by riegaz** [RT-Thread/env-windows#22]
After installing the Windows environment under windows 11 I get the following error when trying to run scons.

Any idea?

`TAARIMI7@TAARIMI7775B C:\Users\TAARIMI7\Downloads\f1c100s\rt-thread\bsp\stm32\stm32f103-dofly-lyc8                    
> scons                                                                                                               
scons: Reading SConscript files ...                                                                                   
AttributeError: 'module' object has no attribute 'run':                                                               
  File "C:\Users\TAARIMI7\Downloads\f1c100s\rt-thread\bsp\stm32\stm32f103-dofly-lyc8\SConstruct", line 48:            
    objs = PrepareBuilding(env, RTT_ROOT, has_libcpu=False)                                                           
  File "C:\Users\TAARIMI7\Downloads\f1c100s\rt-thread\tools\building.py", line 370:                                   
    exports='remove_components'))                                                                                     
  File "c:\users\taarimi7\desktop\env-windows-1.4.1\tools\python27\lib\site-packages\scons\SCons\Script\SConscript.py"
, line 660:                                                                                                           
    return method(*args, **kw)                                                                                        
  File "c:\users\taarimi7\desktop\env-windows-1.4.1\tools\python27\lib\site-packages\scons\SCons\Script\SConscript.py"
, line 597:                                                                                                           
    return _SConscript(self.fs, *files, **subst_kw)                                                                   
  File "c:\users\taarimi7\desktop\env-windows-1.4.1\tools\python27\lib\site-packages\scons\SCons\Script\SConscript.py"
, line 286:                                                                                                           
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)                                             
  File "C:\Users\TAARIMI7\Downloads\f1c100s\rt-thread\components\SConscript", line 15:                                
    objs = objs + SConscript(os.path.join(item, 'SConscript'))                                                        
  File "c:\users\taarimi7\desktop\env-windows-1.4.1\tools\python27\lib\site-packages\scons\SCons\Script\SConscript.py"
, line 660:                                                                                                           
    return method(*args, **kw)                                                                                        
  File "c:\users\taarimi7\desktop\env-windows-1.4.1\tools\python27\lib\site-packages\scons\SCons\Script\SConscript.py"
, line 597:                                                                                                           
    return _SConscript(self.fs, *files, **subst_kw)                                                                   
  File "c:\users\taarimi7\desktop\env-windows-1.4.1\tools\python27\lib\site-packages\scons\SCons\Script\SConscript.py"
, line 286:                                                                                                           
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)                                             
  File "C:\Users\TAARIMI7\Downloads\f1c100s\rt-thread\components\libc\SConscript", line 13:                           
    objs = objs + SConscript(os.path.join(d, 'SConscript'))                                                           
  File "c:\users\taarimi7\desktop\env-windows-1.4.1\tools\python27\lib\site-packages\scons\SCons\Script\SConscript.py"
, line 660:                                                                                                           
    return method(*args, **kw)                                                                                        
  File "c:\users\taarimi7\desktop\env-windows-1.4.1\tools\python27\lib\site-packages\scons\SCons\Script\SConscript.py"
, line 597:                                                                                                           
    return _SConscript(self.fs, *files, **subst_kw)                                                                   
  File "c:\users\taarimi7\desktop\env-windows-1.4.1\tools\python27\lib\site-packages\scons\SCons\Script\SConscript.py"
, line 286:                                                                                                           
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)                                             
  File "C:\Users\TAARIMI7\Downloads\f1c100s\rt-thread\components\libc\compilers\SConscript", line 13:                 
    objs = objs + SConscript(os.path.join(d, 'SConscript'))                                                           
  File "c:\users\taarimi7\desktop\env-windows-1.4.1\tools\python27\lib\site-packages\scons\SCons\Script\SConscript.py"
, line 660:                                                                                                           
    return method(*args, **kw)                                                                                        
  File "c:\users\taarimi7\desktop\env-windows-1.4.1\tools\python27\lib\site-packages\scons\SCons\Script\SConscript.py"
, line 597:                                                                                                           
    return _SConscript(self.fs, *files, **subst_kw)                                                                   
  File "c:\users\taarimi7\desktop\env-windows-1.4.1\tools\python27\lib\site-packages\scons\SCons\Script\SConscript.py"
, line 286:                                                                                                           
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)                                             
  File "C:\Users\TAARIMI7\Downloads\f1c100s\rt-thread\components\libc\compilers\newlib\SConscript", line 8:           
    newlib_version = GetNewLibVersion(rtconfig)                                                                       
  File "C:\Users\TAARIMI7\Downloads\f1c100s\rt-thread\tools\gcc.py", line 160:                                        
    fn = GetHeader(rtconfig, 'picolibc.h')                                                                            
  File "C:\Users\TAARIMI7\Downloads\f1c100s\rt-thread\tools\gcc.py", line 95:                                         
    include_dirs = GetGccDefaultSearchDirs(rtconfig)                                                                  
  File "C:\Users\TAARIMI7\Downloads\f1c100s\rt-thread\tools\gcc.py", line 77:                                         
    proc = subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)                          `

**Comment by mysterywolf** [comment]
Thanks for reporting this problem, we has found it. you can revert da55491608e19c53d5260309a4fb2ccad930cc51 in rt-thread source code to solve this problem. I will fix it.

**Comment by riegaz** [comment]
Thanks, that solved that issue.

Just seconds later I run into this one.

`TAARIMI7@TAARIMI7775B C:\Users\TAARIMI7\Downloads\f1c100s\rt-thread\bsp\stm32\stm32f103-dofly-lyc8
> scons
scons: Reading SConscript files ...
Newlib version: 4.1.0
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build
CC build\applications\main.o
CC build\board\board.o
CC build\board\CubeMX_Config\Src\stm32f1xx_hal_msp.o
CC build\kernel\components\drivers\core\device.o
CC build\kernel\components\drivers\ipc\completion.o
CC build\kernel\components\drivers\ipc\dataqueue.o
CC build\kernel\components\drivers\ipc\pipe.o
CC build\kernel\components\drivers\ipc\ringblk_buf.o
CC build\kernel\components\drivers\ipc\ringbuffer.o
CC build\kernel\components\drivers\ipc\waitqueue.o
CC build\kernel\components\drivers\ipc\workqueue.o
CC build\kernel\components\drivers\misc\pin.o
CC build\kernel\components\drivers\serial\serial.o
CC build\kernel\components\finsh\cmd.o
CC build\kernel\components\finsh\msh.o
CC build\kernel\components\finsh\msh_parse.o
CC build\kernel\components\finsh\shell.o
CC build\kernel\components\libc\compilers\common\cctype.o
CC build\kernel\components\libc\compilers\common\cstdlib.o
CC build\kernel\components\libc\compilers\common\cstring.o
CC build\kernel\components\libc\compilers\common\ctime.o
CC build\kernel\components\libc\compilers\common\cunistd.o
CC build\kernel\components\libc\compilers\common\cwchar.o
CC build\kernel\components\libc\compilers\newlib\syscalls.o
CC build\kernel\libcpu\arm\common\atomic_arm.o
CC build\kernel\libcpu\arm\common\div0.o
CC build\kernel\libcpu\arm\common\showmem.o
AS build\kernel\libcpu\arm\cortex-m3\context_gcc.o
CC build\kernel\libcpu\arm\cortex-m3\cpuport.o
CC build\kernel\src\clock.o
CC build\kernel\src\components.o
CC build\kernel\src\idle.o
C:\Users\TAARIMI7\Downloads\f1c100s\rt-thread\src\idle.c:43:33: error: 'RT_CPUS_NR' undeclared here (not in a function)
   43 | #define _CPUS_NR                RT_CPUS_NR
      |                                 ^~~~~~~~~~
C:\Users\TAARIMI7\Downloads\f1c100s\rt-thread\src\idle.c:48:37: note: in expansion of macro '_CPUS_NR'
   48 | static struct rt_thread idle_thread[_CPUS_NR];
      |                                     ^~~~~~~~
scons: *** [build\kernel\src\idle.o] Error 1
scons: building terminated because of errors.`

I guess this is not env related?

**Comment by mysterywolf** [comment]
before you use scons to compile, you need to use menuconfig cmd to go in the setting UI then exit, it will refresh the rtconfig.h
