### ISSUE TITLE
env中python版本过低

### ISSUE THREAD

**Issue by YukiLauuu** [RT-Thread/env-windows#26]
env使用的python版本为2.7，且在setting中似乎没有自行设置python路径的选项，请问如何解决？

需要解决这个问题是在env中执行pip install toml出错，推测是python版本原因。

![image](https://github.com/RT-Thread/env-windows/assets/56765592/4a2cbe7d-1078-4eba-ad47-4e888a2b8e05)

**Comment by mysterywolf** [comment]
env for windows是一个基于Env封装好的环境，里边预置了python2.7 QEMu和ARM工具链等
如果想要用python3，可以用https://github.com/RT-Thread/env 这个仓库，这个是纯净env，可以自己搭建环境。
https://docs.rtduino.com/#/zh/beginner/env?id=_2-%e5%ae%89%e8%a3%85env%e5%b7%a5%e5%85%b7

**Comment by YukiLauuu** [comment]
> env for windows是一个基于Env封装好的环境，里边预置了python2.7 QEMu和ARM工具链等
> 如果想要用python3，可以用https://github.com/RT-Thread/env 这个仓库，这个是纯净env，可以自己搭建环境。
> https://docs.rtduino.com/#/zh/beginner/env?id=_2-%e5%ae%89%e8%a3%85env%e5%b7%a5%e5%85%b7

好的，感谢
