### ISSUE TITLE
最新v1.5.2版本运行env.exe一直在"clink.bat inject",没有出现命令行

### ISSUE THREAD

**Issue by matlam1989** [RT-Thread/env-windows#29]
![image](https://github.com/RT-Thread/env-windows/assets/17871286/8a89b0e3-dae7-4ecf-a80f-a711922c8491)
使用的是是公司笔记本，window10系统，没有管理员权限，有SentinelOne杀毒软件。

**Comment by ComerLater** [comment]
运行env.bat也是一样吗

**Comment by matlam1989** [comment]
对的，感觉被杀毒软件拦截了，一直hook下个程序



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月20日(周四) 下午2:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RT-Thread/env-windows] 最新v1.5.2版本运行env.exe一直在"clink.bat inject",没有出现命令行 (Issue #29)




 
运行env.bat也是一样吗

**Comment by matlam1989** [comment]
目前我这边只能使用虚拟机运行env工具

**Comment by mysterywolf** [comment]
一定要把杀毒软件关了或者把这个软件的路径加入杀毒软件的白名单
